### ISSUE TITLE
The `latest` version of this package is empty

### ISSUE THREAD

**Issue by drwpow** [bohdanbirdie/vitest-launchdarkly-mock#3]
[See here](https://unpkg.com/browse/vitest-launchdarkly-mock@1.0.1-node-support.0/): the `latest` flag is applied to this `-node-support.0` test version, not the `1.0.0` version.

Suggestion:

```
npm dist-tag add vitest-launchdarkly-mock@1.0.0 latest
```

Will fix the install for most people.

**Comment by bohdanbirdie** [comment]
Solved in https://github.com/bohdanbirdie/vitest-launchdarkly-mock/pull/4
